org.gradle.jvmargs=-Xmx1G
org.gradle.caching=false
org.gradle.configuration-cache=false

# Plugin Metadata
plugin_group=Team_Berry
plugin_name=Save The Kweebecs
plugin_description=Explore. Die. Repeat. Master unique skills and artifacts in this ultimate Roguelike to Save the Kweebecs!
plugin_author=Varrell | Nalo | Arc | Light06
plugin_website=
plugin_main_entrypoint=com.Team_Berry.Save_The_Kweebec
plugin_version=1.7
server_version=2026.03.26-89796e57b
